# https://fly.io/docs/reference/configuration/

app = 'pressxtohonk-devbox'
primary_region = 'sin'

[mounts]
  source = "data"
  destination = "/data"
  initial_size = "1gb" # $0.15¢ / gb / month

[[vm]]
  memory = "256mb"
  size = 'shared-cpu-1x'
  # memory = "2gb"
  # size = 'performance-1x'
